version: '3'
services:
  postgres:
    image: postgres:13.1
    container_name: postgres_dc
    environment:
      POSTGRES_USER: huilong #在此填写postgres的用户名
      POSTGRES_DB: postgres #在此填写postgres的数据库名，默认是 postgres
      POSTGRES_PASSWORD: 123456 #在此填写posgres的数据库密码
    volumes:
      - ./init:/docker-entrypoint-initdb.d/ # 初始sql
    ports:
      - "5432:5432"
