version: '2'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    image: "docker.io/mysql:8.0"
    volumes:
    - ./init:/docker-entrypoint-initdb.d/ # 初始sql
    container_name: mysql
    ports:
      - "3306:3306"

